name: Deploy ICOK Fund Dashboard

on:
  # 수동 실행
  workflow_dispatch:

  # 매일 오전 9시 KST (= UTC 00:00) 자동 배포
  schedule:
    - cron: '0 0 * * *'

  # main 브랜치에 push 시 자동 배포
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

# 동시 배포 방지
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 타임스탬프를 index.html에 기록 (캐시 무효화 + 최신화 시각 표시)
      - name: Update timestamp
        run: |
          TIMESTAMP=$(TZ="Asia/Seoul" date "+%Y-%m-%d %H:%M KST")
          echo "Deploying at: $TIMESTAMP"
          # HTML 내 placeholder가 있으면 교체 (선택사항)
          sed -i "s/__BUILD_TIME__/$TIMESTAMP/g" index.html || true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
